#include<stdio.h>
#include<conio.h>
void main()
{
printf("\n\n\n\n\nname          =  sumit");
printf("\nfather's name = pawan kr.gupta");
printf("\nmother's name = pushplata devi");
printf("\nprogram       = BCA  ");
printf("\ncollege       = tecnia institute");
printf("\nshift         = second");
printf("\ntias ID       = tias/bca/2021-24/1254");
printf("\ncontact no.   = 9953699367\n\n\n");
getch();
}
